# Dockerfile.site2

FROM nginx:alpine

# Копируем конфигурацию для site2
COPY ./nginx.site2.conf /etc/nginx/nginx.conf

# Копируем статические файлы для site2
COPY ./site2/dist /usr/share/nginx/html

EXPOSE 80
