version: '3.8'

services:
  nginx:
    build:
      context: ../  # Указывает на корневую папку проекта
      dockerfile: docker/Dockerfile.nginx
    volumes:
      - ../dist:/usr/share/nginx/html  # Монтируем папку dist
      - ../docker/nginx.conf:/etc/nginx/nginx.conf  # Исправлен путь к конфигурации nginx
    ports:
      - "8080:80"  # Проброс порта

  api:
    build:
      context: ../api  # Папка с Dockerfile.api
      dockerfile: ../docker/Dockerfile.api  # Исправлен путь к Dockerfile.api
    ports:
      - "3000:3000"  # Проброс порта для API
    depends_on: 
      - nginx

networks:
  default:
    external:
      name: nginx_network  # Или любое другое имя сети, если требуется

