# Используем официальный образ Nginx как базовый
FROM nginx:latest

# Удаляем стандартные конфигурационные файлы
RUN rm /etc/nginx/conf.d/default.conf

# Копируем свою конфигурацию Nginx
COPY ./docker/nginx.conf /etc/nginx/nginx.conf
#COPY conf.d /etc/nginx/conf.d

# Копируем собранные статические файлы в контейнер
COPY dist /usr/share/nginx/html

# Открываем порт 80
EXPOSE 80
