version: '3'
services:
  api:
    build:
      context: ../api
      dockerfile: Dockerfile.api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  nginx:
    build:
      context: ../nginx
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: donutbar
    volumes:
      - ./databases:/docker-entrypoint-initdb.d
