# docker-compose.yml
version: '3.8'

services:
  api:
    build:
      context: ..  # Убедитесь, что контекст указывает на правильный путь
      dockerfile: ./docker/Dockerfile.api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - mysql_orders
      - mysql_products
      - mysql_customers
      - mysql_admins  # Добавляем зависимость от новой базы данных

  nginx:
    build:
      context: ..  # Убедитесь, что контекст указывает на правильный путь
      dockerfile: ./docker/Dockerfile.nginx
    ports:
      - "8080:80"
    depends_on:
      - api
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf

  mysql_orders:
    image: mysql:8.0
    container_name: mysql_orders
    environment:
      MYSQL_ROOT_PASSWORD: spore23
      MYSQL_DATABASE: orders_db
      MYSQL_USER: user
      MYSQL_PASSWORD: spore23
    ports:
      - "3307:3306"
    volumes:
      - mysql-orders-data:/var/lib/mysql

  mysql_products:
    image: mysql:8.0
    container_name: mysql_products
    environment:
      MYSQL_ROOT_PASSWORD: spore23
      MYSQL_DATABASE: products_db
      MYSQL_USER: user
      MYSQL_PASSWORD: spore23
    ports:
      - "3306:3306"
    volumes:
      - mysql-products-data:/var/lib/mysql

  mysql_customers:
    image: mysql:8.0
    container_name: mysql_customers
    environment:
      MYSQL_ROOT_PASSWORD: spore23
      MYSQL_DATABASE: customers_db
      MYSQL_USER: user
      MYSQL_PASSWORD: spore23
    ports:
      - "3308:3306"
    volumes:
      - mysql-customers-data:/var/lib/mysql

  mysql_admins:  # Новая база данных для учетных записей администраторов
    image: mysql:8.0
    container_name: mysql_admins
    environment:
      MYSQL_ROOT_PASSWORD: spore23
      MYSQL_DATABASE: admins_db  # Название базы данных
      MYSQL_USER: user
      MYSQL_PASSWORD: spore23
    ports:
      - "3309:3306"  # Используем другой порт, чтобы избежать конфликта
    volumes:
      - mysql-admins-data:/var/lib/mysql  # Добавляем volume для хранения данных

volumes:
  mysql-orders-data:
  mysql-products-data:
  mysql-customers-data:
  mysql-admins-data:  # Volume для базы данных администраторов
