# Dockerfile.site1

FROM nginx:alpine

# Копируем конфигурацию для site1
COPY ./nginx.site1.conf /etc/nginx/nginx.conf

# Копируем статические файлы для site1
COPY ./site1/dist /usr/share/nginx/html

EXPOSE 80