# Dockerfile.api
FROM node:16

# Установите рабочую директорию внутри контейнера
WORKDIR /usr/src/app

# Копируйте файлы package.json и package-lock.json
COPY api/package*.json ./

# Установите зависимости
RUN npm install

# Копируйте весь исходный код в рабочую директорию
COPY api/ ./

# Откройте порт, на котором будет работать ваше API
EXPOSE 3000

# Команда для запуска вашего приложения
CMD ["node", "index.js"]